version: '3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
 
  ui:
    image: ${USERNAME}/ui:${VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui


  post:
    image: ${USERNAME}/post:${VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USERNAME}/comment:${VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    external_links:
      - post_db:comment_db

volumes:
  post_db:

networks:
  front_net:
    ipam:
      config:
      - subnet: ${FRONEND_SUBNET}

  back_net:
    ipam:
      config:
      - subnet: ${BACKEND_SUBNET}
