version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
 
  ui:
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${VERSION}
    networks:
      - back_net
      - front_net

  comment:
    image: ${USERNAME}/comment:${VERSION}
    networks:
      - back_net
      - front_net
    external_links:
      - post_db:comment_db

volumes:
  post_db:

networks:
  front_net:
    ipam:
      config:
      - subnet: ${FRONEND_SUBNET}

  back_net:
    ipam:
      config:
      - subnet: ${BACKEND_SUBNET}
