---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: comment
  labels:
    app: reddit
    component: comment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: comment
  template:
    metadata:
      name: comment-prod
      labels:
        app: reddit
        component: comment
    spec:
      containers:
        - image: darthnitrox/comment
          name: comment
          env:
            - name: COMMENT_DATABASE_HOST
              value: comment-db